name: davinciweb
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


#------------------Paquetes------------------#
dependencies:
  flutter:
    sdk: flutter

  #-------Utilidades-------#
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  image_picker: ^1.1.1
  
  #-------Iconos-------#
  cupertino_icons: ^1.0.2

  #-------Firebase-------#
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  
  #-------Manejo de estados de widgets-------#
  get: ^4.6.5
  get_storage: ^2.1.1

#-------Flutter-------#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

#------------------Assets------------------#
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/

  fonts:
    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/MerriweatherSans-Regular.ttf

#------------------Splash Screen------------------#
flutter_native_splash:
  android: false
  ios: false
  web: true
  color: "#E2EDF1"
  image: "assets/logos/davinciLogoRounded.png"
  web_image_mode: center